name: Publish NuGet release

on:
  create:
    branches: 
      - release/**

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      BUILD_CONFIG: 'Release'

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

    - name: Test
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-build --verbosity normal

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_APIKEY}}
